Validate change in pfcon config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -96,6 +96,36 @@ jobs:
         exit $status
     - name: Test NodePort access
       run: curl --fail-with-body http://localhost:32000/api/v1/
+    - name: Disabling pfcon should not be allowed
+      if: matrix.pfconEnabled
+      run: |
+        set +e
+        expected='CUBE currently depends on pfcon configured in "innetwork" mode for its storage, volume, so you cannot set .pfcon.enabled=false or .pfcon.pfcon.config.innetwork=false'
+        output="$(helm upgrade -n ghactions khris-test ./charts/chris --reuse-values --set pfcon.enabled=false)"
+        rc=$?
+        echo "$output"
+        if [ "$rc" != '0' ]; then
+          echo "::error ::Expected command to fail but it didn't"
+          exit $rc
+        elif ! [[ "$output" = *"$expected"* ]]; then
+          echo "::error ::Unexpected output"
+          exit 1
+        fi
+    - name: Enabling pfcon should not be allowed
+      if: !matrix.pfconEnabled
+      run: |
+          set +e
+          expected='CUBE is currently using its own volume, so you cannot set .pfcon.enabled=true or .pfcon.pfcon.config.innetwork=true'
+          output="$(helm upgrade -n ghactions khris-test ./charts/chris --reuse-values --set pfcon.enabled=true)"
+          rc=$?
+          echo "$output"
+          if [ "$rc" != '0' ]; then
+            echo "::error ::Expected command to fail but it didn't"
+            exit $rc
+          elif ! [[ "$output" = *"$expected"* ]]; then
+            echo "::error ::Unexpected output"
+            exit 1
+          fi
     - name: Uninstall chart
       run: helm uninstall -n ghactions khris-test
     - name: Delete namespace
